Change genre colors, banners and fixed some typos
gamehelp16/monstercat-browser-old pull request #17
Opened 2016-11-04 23:34 UTC by GiovanniMCMXCIX

demo at: https://giovannimcmxcix.github.io/monstercat-browser

2016-11-04 23:35 UTC, GiovanniMCMXCIX commented
sorry for github messing the json files

2016-11-05 14:00 UTC, gamehelp16 requested changes
Thank you for your contribution! There's a little change you need to make before I merge the PR.

And also I have a few comments:
1. The albumdata.html is not intended to have a "clean" code, so I guess you don't need to improve it next time.
2. What was the .idea folder about? I'm actually curious :stuck_out_tongue_closed_eyes:

2016-11-05 14:00 UTC, gamehelp16 commented on styles.css
> -        -moz-transform: .05s linear all;
The `-moz-transform` and `transform` properties should not be deleted since it means that the animation will only appear on webkit based browsers.

2016-11-05 14:44 UTC, GiovanniMCMXCIX commented on styles.css
> -        -moz-transform: .05s linear all;
i deteted those because my code editor was giving `Mismatched property value` error and idk what to do about it

2016-11-05 14:44 UTC, GiovanniMCMXCIX commented
`.idea` folder was from my code editor

2016-11-06 04:31 UTC, gamehelp16 commented
Umm.. to be honest I don't think singles are suitable to put into the EP section, and also I don't think making a singles section is good either since there are tons of them and most of them contain only one track.

2016-11-06 09:53 UTC, GiovanniMCMXCIX commented
I've put MCS503 because is mostly as an EP like MCF003 is

2016-11-07 10:43 UTC, gamehelp16 commented
Ah, okay.

2016-11-07 10:43 UTC, merged